# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bbmp',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/bbmp',
                'lib_path': 'bbmp'},
  'syms': {'bbmp.core': {'bbmp.core.say_hello': ('bbmp.html#say_hello', 'bbmp/core.py')}}}